/* ケロちゃん あたま ぐんぐん in every language: [Tiếng Việt, English, 한국어] (see js/lang.js).
   ケロはかせ speaks Japanese with recorded clips (VOICEVOX:ずんだもん); in the other languages the phone reads
   these lines aloud (js/voice.js), so the lines he only says (never shown) are here too. */
Lang.add({
  // ---------------------------------------------------------------- title, menus
  'ケロちゃん あたま ぐんぐん': ['Kero Luyện Não', 'Kero Brain Boost', '케로 두뇌 쑥쑥'],
  'だれが あそぶ？': ['Ai chơi nào?', 'Who is playing?', '누가 할래?'],
  'メニューに もどる': ['Về menu', 'Back to the menu', '메뉴로 돌아가기'],
  'ホームに ついか': ['Thêm vào màn hình', 'Add to Home', '홈 화면에 추가'],
  'こえ': ['Giọng nói', 'Voice', '목소리'],
  'こうかおん': ['Âm thanh', 'Sound effects', '효과음'],
  'おんがく': ['Nhạc', 'Music', '음악'],
  'きょうの チェック': ['Kiểm tra hôm nay', "Today's Check", '오늘의 체크'],
  'できた': ['Xong', 'Done', '완료'],
  'トレーニング': ['Luyện tập', 'Training', '트레이닝'],
  'スタンプ': ['Con dấu', 'Stamps', '도장'],
  'きろく': ['Kỷ lục', 'Records', '기록'],
  'おみせ': ['Cửa hàng', 'Shop', '가게'],
  'ふたりで': ['Hai người', 'Two players', '둘이서'],
  'ふたりで あそぶ': ['Hai người chơi', 'Two players', '둘이서 놀기'],
  'もどる': ['Quay lại', 'Back', '뒤로'],
  'やめる': ['Thôi', 'Stop', '그만'],
  'とじる': ['Đóng', 'Close', '닫기'],
  'つぎへ': ['Tiếp theo', 'Next', '다음'],
  'もういちど': ['Chơi lại', 'Again', '다시 하기'],
  'まえの つき': ['Tháng trước', 'Previous month', '이전 달'],
  'つぎの つき': ['Tháng sau', 'Next month', '다음 달'],
  'なまえなし': ['Chưa có tên', 'No name', '이름 없음'],
  'こえ：{credit}': ['Giọng nói: {credit}', 'Voice: {credit}', '목소리: {credit}'],
  '日本語の こえ：{credit}': ['Giọng tiếng Nhật: {credit}', 'Japanese voice: {credit}', '일본어 목소리: {credit}'],
  'おとな': ['Người lớn', 'Grown-up', '어른'],
  'こども': ['Trẻ em', 'Child', '어린이'],
  '{name}、': ['{name} ơi, ', '{name}, ', '{name}, '],
  'ケロはかせ「{t}」': ['Giáo sư Kero: “{t}”', 'Dr. Kero: “{t}”', '케로 박사: “{t}”'],
  '（{t}）': [' ({t})', ' ({t})', ' ({t})'],

  // ---------------------------------------------------------------- the list and a training's page
  'スタンプ あと {n}こ': ['Còn {n} con dấu', '{n} more stamps', '도장 {n}개 더'],
  'あたらしい': ['Mới', 'New', '새로'],
  'れんしゅう': ['Luyện tập', 'Practice', '연습'],
  'はじめる': ['Bắt đầu', 'Start', '시작'],
  'いちばん：{best}': ['Tốt nhất: {best}', 'Best: {best}', '최고: {best}'],
  ' あと{n}こ': [' còn {n}', ' {n} more', ' {n}개 더'],
  'スタート！': ['Bắt đầu!', 'Go!', '시작!'],
  'けす': ['Xóa', 'Del', '지우기'],
  'チェック': ['Kiểm tra', 'Check', '체크'],
  'かんたん': ['Dễ', 'Easy', '쉬움'],
  'ふつう': ['Vừa', 'Normal', '보통'],
  'むずかしい': ['Khó', 'Hard', '어려움'],
  'おとな かんたん': ['Người lớn · Dễ', 'Grown-up · Easy', '어른 · 쉬움'],
  'おとな ふつう': ['Người lớn · Vừa', 'Grown-up · Normal', '어른 · 보통'],
  'おとな むずかしい': ['Người lớn · Khó', 'Grown-up · Hard', '어른 · 어려움'],
  'はやさ': ['Tốc độ', 'Speed', '속도'],
  'きおく': ['Trí nhớ', 'Memory', '기억력'],
  'がまん・しゅうちゅう': ['Kiên nhẫn · Tập trung', 'Self-control · Focus', '참을성 · 집중력'],
  'もじ・おと・パズル': ['Chữ · Âm nhạc · Câu đố', 'Letters · Music · Puzzles', '글자 · 소리 · 퍼즐'],
  'がまん': ['Kiên nhẫn', 'Self-control', '참을성'],
  'ちょっと おやすみ': ['Nghỉ một chút', 'Taking a break', '잠깐 쉬어'],
  'つづける': ['Chơi tiếp', 'Continue', '계속하기'],

  // ---------------------------------------------------------------- the trainings: names and how to play
  'けいさん': ['Tính nhẩm', 'Quick Math', '계산'],
  'いちばん おおきい かず': ['Số lớn nhất', 'Biggest Number', '가장 큰 수'],
  'じゅんばん ぴょんぴょん': ['Nhảy theo thứ tự', 'Hop in Order', '순서대로 폴짝'],
  'ぱっと おぼえて': ['Nhớ thật nhanh', 'Quick Memory', '반짝 기억'],
  'なんにん いるかな？': ['Có mấy người?', 'How Many Inside?', '몇 명 있을까?'],
  'さっきの え': ['Hình vừa rồi', 'The Last Picture', '아까 그 그림'],
  'あとだし じゃんけん': ['Oẳn tù tì ra sau', 'Late Rock-Paper-Scissors', '뒤늦게 가위바위보'],
  'ジャンプで タッチ': ['Vừa nhảy vừa chạm', 'Jump & Tap', '점프하며 터치'],
  'とり かぞえ': ['Đếm chim', 'Count the Birds', '새 세기'],
  'ことば つくり': ['Ghép chữ', 'Word Builder', '낱말 만들기'],
  'ピアノ': ['Đàn piano', 'Piano', '피아노'],
  'えあわせ すうどく': ['Sudoku hình', 'Picture Sudoku', '그림 스도쿠'],
  'なにが あった？': ['Đã có gì nhỉ?', 'What Did You See?', '뭐가 있었지?'],
  'はこ かぞえ': ['Đếm khối', 'Count the Blocks', '블록 세기'],
  'しきを みて こたえの\nすうじを タッチしてね！': ['Nhìn phép tính rồi chạm vào\nsố là đáp án nhé!', 'Look at the sum and tap\nthe number of the answer!', '식을 보고 답이 되는\n숫자를 터치해 봐!'],
  'ふうせんの なかで\nいちばん おおきい かずを タッチ！\nふうせんの おおきさに だまされないでね': ['Trong các quả bóng,\nchạm vào số lớn nhất!\nĐừng để quả bóng to nhỏ đánh lừa nhé', 'Tap the biggest number\namong the balloons!\nDon\'t be fooled by their sizes', '풍선 중에서\n가장 큰 수를 터치!\n풍선 크기에 속지 마'],
  'はっぱの すうじを\n1から じゅんばんに タッチすると\nぴょんぴょん とんでいくよ！': ['Chạm vào các số trên lá\ntheo thứ tự từ 1,\nbạn nhỏ sẽ nhảy tưng tưng!', 'Tap the numbers on the leaves\nin order from 1\nand hop, hop, hop along!', '잎사귀의 숫자를\n1부터 차례로 터치하면\n폴짝폴짝 뛰어가!'],
  'たまごの すうじを ぱっと おぼえて\n1から じゅんばんに タッチしてね！': ['Nhớ thật nhanh các số trên trứng\nrồi chạm theo thứ tự từ 1 nhé!', 'Remember the numbers on the eggs\nand tap them in order from 1!', '알의 숫자를 반짝 기억하고\n1부터 차례로 터치해 봐!'],
  'おうちに はいったり でたり…\nさいごに おうちの なかに\nなんにん いるか こたえてね！': ['Mọi người vào nhà, ra nhà…\nCuối cùng trong nhà\ncó mấy người nhỉ?', 'People go in and out…\nAt the end, how many\nare in the house?', '집에 들어갔다 나왔다…\n마지막에 집 안에\n몇 명 있는지 맞혀 봐!'],
  'えが 1まいずつ でてくるよ\nひとつ まえに でた えを\nしたから えらんでね！': ['Từng hình một hiện ra.\nChọn ở dưới hình\nvừa hiện ra ngay trước nhé!', 'Pictures come one at a time.\nPick the one that came\njust before, from below!', '그림이 한 장씩 나와\n바로 전에 나온 그림을\n아래에서 골라 봐!'],
  'ケロはかせの てを みて\n「かって」なら かつ て、「まけて」なら まける てを\nはやく だしてね！': ['Nhìn tay Giáo sư Kero:\n“Thắng” thì ra tay thắng, “Thua” thì ra tay thua,\nra thật nhanh nhé!', 'Look at Dr. Kero\'s hand:\n“Win!” — play the hand that wins, “Lose!” — the one that loses,\nas fast as you can!', '케로 박사의 손을 보고\n「이겨」면 이기는 손, 「져」면 지는 손을\n빨리 내 봐!'],
  'いしが きたら ジャンプ！\nおなじ ときに したの おおきい かずを\nタッチしてね。ふたつ いっしょに できるかな？': ['Đá lăn tới thì nhảy!\nCùng lúc đó chạm vào số lớn hơn ở dưới.\nLàm hai việc cùng lúc được không?', 'Jump when a stone comes!\nAt the same time, tap the bigger number below.\nCan you do both at once?', '돌이 오면 점프!\n동시에 아래의 큰 수를\n터치해. 둘 다 같이 할 수 있을까?'],
  'もりの なかに いる\nことりだけを かぞえてね！\nちょうちょや むしは かぞえないよ': ['Chỉ đếm những chú chim nhỏ\ntrong rừng thôi nhé!\nKhông đếm bướm hay côn trùng', 'Count only the little birds\nin the forest!\nNot the butterflies or bugs', '숲속에 있는\n작은 새만 세어 봐!\n나비나 벌레는 세지 않아'],
  'えを みて なまえの もじを\nじゅんばんに タッチしてね！': ['Nhìn hình rồi chạm vào\ncác chữ của tên theo thứ tự nhé!', 'Look at the picture and tap\nthe letters of its name in order!', '그림을 보고 이름의 글자를\n차례로 터치해 봐!'],
  'うえの おんぷと おなじ けんばんを\nじゅんばんに おしてね！\nさいごに きょくを ぜんぶ きけるよ': ['Nhấn phím giống nốt nhạc ở trên\ntheo thứ tự nhé!\nCuối cùng được nghe cả bài', 'Press the keys that match\nthe notes above, in order!\nAt the end you hear the whole song', '위의 음표와 같은 건반을\n차례로 눌러 봐!\n마지막에 곡을 다 들을 수 있어'],
  'たて・よこ・へやに\nおなじ たまごが 1つずつ はいるように\nあいてる マスを うめてね！': ['Điền vào ô trống sao cho\nmỗi hàng, mỗi cột, mỗi phòng\nđều có mỗi loại trứng một quả!', 'Fill the empty squares so that\nevery row, column and room\nhas one of each egg!', '가로·세로·방마다\n같은 알이 하나씩 들어가게\n빈칸을 채워 봐!'],
  'えを よく おぼえてね！\nそのあと たくさんの えの なかから\nみた えを えらぶよ': ['Nhớ thật kỹ các hình nhé!\nSau đó chọn những hình đã thấy\ntrong thật nhiều hình', 'Remember the pictures well!\nThen pick the ones you saw\nfrom lots of pictures', '그림을 잘 기억해!\n그다음 많은 그림 중에서\n본 그림을 골라'],
  'つみきが すこしだけ みえるよ\nいくつ あったかな？': ['Các khối gỗ chỉ hiện ra một chút.\nCó bao nhiêu khối nhỉ?', 'The blocks show for a moment.\nHow many were there?', '블록이 잠깐만 보여\n몇 개 있었을까?'],

  // ---------------------------------------------------------------- inside the trainings
  'よーい…': ['Chuẩn bị…', 'Ready…', '준비…'],
  'いちばん おおきい かずは どれ？': ['Số nào lớn nhất?', 'Which is the biggest number?', '가장 큰 수는 뭘까?'],
  'おぼえてね！': ['Nhớ nhé!', 'Remember!', '기억해!'],
  '1から じゅんばんに タッチ！': ['Chạm theo thứ tự từ 1!', 'Tap in order from 1!', '1부터 차례로 터치!'],
  'ざんねん！ こたえは これ': ['Tiếc quá! Đáp án là đây', 'Oops! Here is the answer', '아쉬워! 정답은 이거야'],
  'おうちの なかに なんにん？': ['Trong nhà có mấy người?', 'How many in the house?', '집 안에 몇 명?'],
  'こたえは {n}にん': ['Đáp án: {n} người', 'The answer is {n}', '정답은 {n}명'],
  'よく みててね！': ['Nhìn kỹ nhé!', 'Watch carefully!', '잘 봐!'],
  'おうちの なかに なんにん いるかな？': ['Trong nhà có mấy người nhỉ?', 'How many are in the house?', '집 안에 몇 명 있을까?'],
  'こたえは {n}にん だよ': ['Đáp án là {n} người nhé', 'The answer is {n}', '정답은 {n}명이야'],
  'この えを おぼえてね': ['Nhớ hình này nhé', 'Remember this picture', '이 그림을 기억해'],
  'よく みてね': ['Nhìn kỹ nhé', 'Look carefully', '잘 봐'],
  'いまの え は どれ？': ['Hình bây giờ là hình nào?', 'Which is the picture now?', '지금 그림은 뭘까?'],
  'ひとつ まえの え は どれ？': ['Hình ngay trước là hình nào?', 'Which one came just before?', '바로 전 그림은 뭘까?'],
  'ふたつ まえの え は どれ？': ['Hình trước đó hai lượt là hình nào?', 'Which one was two pictures ago?', '두 번 전 그림은 뭘까?'],
  'グー': ['Búa', 'Rock', '바위'],
  'チョキ': ['Kéo', 'Scissors', '가위'],
  'パー': ['Bao', 'Paper', '보'],
  'かって！': ['Thắng!', 'Win!', '이겨!'],
  'まけて！': ['Thua!', 'Lose!', '져!'],
  'あいこ！': ['Hòa!', 'Draw!', '비겨!'],
  'かって': ['Thắng', 'Win', '이겨'],
  'まけて': ['Thua', 'Lose', '져'],
  'あいこ': ['Hòa', 'Draw', '비겨'],
  'こんどは かって！': ['Giờ thì thắng nhé!', 'Now win!', '이번엔 이겨!'],
  'こんどは まけて！': ['Giờ thì thua nhé!', 'Now lose!', '이번엔 져!'],
  'こんどは あいこ！': ['Giờ thì hòa nhé!', 'Now draw!', '이번엔 비겨!'],
  'じゃん けん…': ['Oẳn tù tì…', 'Rock, paper…', '가위바위…'],
  'この ことばを みてね': ['Nhìn chữ này nhé', 'Look at this word', '이 말을 잘 봐'],
  'ことばが かわったよ！': ['Chữ đổi rồi!', 'The word changed!', '말이 바뀌었어!'],
  'ジャンプ': ['Nhảy', 'Jump', '점프'],
  'おおきい かずを タッチ！': ['Chạm số lớn hơn!', 'Tap the bigger number!', '큰 수를 터치!'],
  'ことりは なんわ？': ['Có mấy chú chim?', 'How many birds?', '새는 몇 마리?'],
  'こたえは {n}わ': ['Đáp án: {n} con', 'The answer is {n}', '정답은 {n}마리'],
  'えの なまえを つくろう！': ['Ghép tên của hình nào!', "Spell the picture's name!", '그림의 이름을 만들자!'],
  '{word}！': ['{word}!', '{word}!', '{word}!'],
  'たて・よこ・へやに おなじ たまごは 1つ！': ['Mỗi hàng, cột, phòng: mỗi loại trứng một quả!', 'One of each egg in every row, column and room!', '가로·세로·방마다 같은 알은 하나!'],
  'たて・よこ・へやに おなじ すうじは 1つ！': ['Mỗi hàng, cột, phòng: mỗi số một lần!', 'One of each number in every row, column and room!', '가로·세로·방마다 같은 숫자는 하나!'],
  'あいてる マスを タッチ！': ['Chạm vào ô trống!', 'Tap an empty square!', '빈칸을 터치!'],
  'おぼえた！': ['Nhớ rồi!', 'Got it!', '기억했어!'],
  'この えを おぼえてね！': ['Nhớ các hình này nhé!', 'Remember these pictures!', '이 그림들을 기억해!'],
  'みた えを えらんでね（{a} / {b}）': ['Chọn hình đã thấy ({a} / {b})', 'Pick what you saw ({a} / {b})', '본 그림을 골라 ({a} / {b})'],
  'えを よく おぼえてね': ['Nhớ kỹ các hình nhé', 'Remember the pictures well', '그림을 잘 기억해'],
  'さっき みた えを {n}まい えらんでね': ['Chọn {n} hình vừa thấy nhé', 'Pick the {n} pictures you saw', '아까 본 그림 {n}장을 골라'],
  'びょう': ['giây', 's', '초'],

  // ---------------------------------------------------------------- results
  '{s}びょう': ['{s} giây', '{s} s', '{s}초'],
  '・まちがい {n}': [' · sai {n}', ' · {n} wrong', ' · 실수 {n}'],
  '{a}もん せいかい（{b}もん）': ['Đúng {a}/{b} câu', '{a} of {b} right', '{b}문제 중 {a}개 정답'],
  'とんだ {o}・タッチ {t}・ミス {m}': ['Nhảy {o} · Chạm {t} · Lỗi {m}', 'Jumps {o} · Taps {t} · Misses {m}', '점프 {o} · 터치 {t} · 실수 {m}'],
  'おぼえた かず {s}・せいかい {a}もん（{b}もん）': ['Nhớ được {s} · Đúng {a}/{b} câu', 'Remembered {s} · {a} of {b} right', '기억한 수 {s} · {b}문제 중 {a}개 정답'],
  'ちいさい じゅんに タッチ！': ['Chạm từ số nhỏ nhất!', 'Tap from the smallest!', '작은 수부터 터치!'],
  'あたり {h}・まちがい {w}（{n}まい）': ['Đúng {h} · Sai {w} ({n} hình)', '{h} right · {w} wrong ({n} pictures)', '맞음 {h} · 틀림 {w} ({n}장)'],
  'まちがい {m}かい・{time}': ['Sai {m} lần · {time}', '{m} mistakes · {time}', '실수 {m}번 · {time}'],
  'リストへ': ['Danh sách', 'List', '목록으로'],
  '{animal}！': ['{animal}!', '{animal}!', '{animal}!'],
  'じこベスト！': ['Kỷ lục mới!', 'Personal best!', '자기 최고!'],
  'かたつむり': ['Ốc sên', 'Snail', '달팽이'],
  'かめ': ['Rùa', 'Turtle', '거북이'],
  'ペンギン': ['Chim cánh cụt', 'Penguin', '펭귄'],
  'カンガルー': ['Chuột túi', 'Kangaroo', '캥거루'],
  'うま': ['Ngựa', 'Horse', '말'],
  'チーター': ['Báo săn', 'Cheetah', '치타'],
  'はやぶさ': ['Chim ưng', 'Falcon', '매'],
  'かたつむりは のんびりやさん。つぎは もっと はやく なるかな？': ['Ốc sên thong thả lắm. Lần sau nhanh hơn nhé?', 'The snail takes it easy. Faster next time?', '달팽이는 느긋해. 다음엔 더 빨라질까?'],
  'かめさんは ゆっくり だけど がんばりやさん！': ['Rùa chậm nhưng rất chăm chỉ!', 'The turtle is slow but never gives up!', '거북이는 느리지만 열심히 해!'],
  'ペンギンは よちよち あるくけど およぐのは はやいんだよ': ['Chim cánh cụt đi lạch bạch nhưng bơi nhanh lắm đấy', 'Penguins waddle, but they swim fast!', '펭귄은 뒤뚱뒤뚱 걷지만 헤엄은 빨라'],
  'カンガルーは おおきな ジャンプで すすむよ！': ['Chuột túi nhảy những bước thật xa!', 'Kangaroos move with big jumps!', '캥거루는 크게 뛰면서 가!'],
  'うまは ぱかぱか はやく はしるよ！': ['Ngựa phi lộc cộc thật nhanh!', 'Horses gallop fast — clip-clop!', '말은 다그닥다그닥 빨리 달려!'],
  'チーターは いちばん はやく はしる どうぶつ なんだよ！': ['Báo săn là con vật chạy nhanh nhất đấy!', 'The cheetah is the fastest runner of all!', '치타는 가장 빨리 달리는 동물이야!'],
  'はやぶさは せかいで いちばん はやい とり なんだよ！': ['Chim ưng là loài chim nhanh nhất thế giới đấy!', 'The falcon is the fastest bird in the world!', '매는 세상에서 가장 빠른 새야!'],

  // ---------------------------------------------------------------- ケロはかせ's lines
  'おはよう！': ['Chào buổi sáng!', 'Good morning!', '좋은 아침!'],
  'こんにちは！': ['Xin chào!', 'Hello!', '안녕!'],
  'こんばんは！': ['Chào buổi tối!', 'Good evening!', '좋은 저녁이야!'],
  'きょうも あたまの たいそう しよう！': ['Hôm nay mình cùng luyện não nào!', "Let's exercise our brains today!", '오늘도 두뇌 체조 하자!'],
  'まいにち すこしずつ やると あたまが ぐんぐん そだつよ': ['Mỗi ngày một chút, trí não lớn nhanh lắm đó', 'A little every day makes your brain grow and grow!', '매일 조금씩 하면 두뇌가 쑥쑥 자라!'],
  'どの トレーニングに する？': ['Hôm nay chơi bài nào?', 'Which training shall we do?', '어떤 트레이닝 할래?'],
  'はじめまして！ ケロはかせ だよ。まいにち いっしょに あたまの たいそう しようね！': ['Chào bạn! Tớ là Giáo sư Kero. Mỗi ngày cùng tớ luyện não nhé!', "Nice to meet you! I'm Dr. Kero. Let's exercise our brains together every day!", '반가워! 난 케로 박사야. 매일 같이 두뇌 체조 하자!'],
  'まずは きょうの チェックから やってみる？': ['Trước tiên, thử kiểm tra hôm nay nhé?', "Shall we start with today's check?", '먼저 오늘의 체크부터 해 볼까?'],
  'きょうの チェックは できたね！ トレーニングも やってみよう': ['Kiểm tra hôm nay xong rồi! Giờ luyện tập thêm nhé', "Today's check is done! Let's try some training too", '오늘의 체크는 끝났어! 트레이닝도 해 보자'],
  'きょうは たくさん がんばったね！ つづきは また あした！': ['Hôm nay cố gắng nhiều rồi! Mai chơi tiếp nhé!', 'You worked hard today! More tomorrow!', '오늘 정말 열심히 했어! 내일 또 하자!'],
  'あたらしい トレーニングが ふえたよ！': ['Có bài luyện tập mới rồi!', 'A new training is here!', '새 트레이닝이 생겼어!'],
  'ピアノの あたらしい きょくが ふえたよ！': ['Có bài đàn piano mới rồi!', 'A new piano song is here!', '피아노 새 곡이 생겼어!'],
  'すごい！ いままでで いちばんだよ！': ['Tuyệt quá! Tốt nhất từ trước tới giờ!', 'Wow! Your best ever!', '대단해! 지금까지 중 최고야!'],
  'じこベスト！ やったね！': ['Kỷ lục mới! Giỏi quá!', 'A new personal best! Yay!', '자기 최고 기록! 해냈다!'],
  'はじめての きろく だね！': ['Kỷ lục đầu tiên đó!', 'Your first record!', '첫 기록이야!'],
  'よく できました！': ['Giỏi lắm!', 'Well done!', '잘했어!'],
  'いい ちょうし！': ['Đang tốt lắm!', "You're doing great!", '좋은 흐름이야!'],
  'がんばったね！': ['Cố gắng lắm!', 'Good effort!', '열심히 했구나!'],
  'すばらしい！': ['Tuyệt vời!', 'Wonderful!', '훌륭해!'],
  'だいじょうぶ！ ゆっくりで いいよ': ['Không sao! Cứ từ từ nhé', "It's OK! Take your time", '괜찮아! 천천히 해도 돼'],
  'つぎは もっと できるよ！': ['Lần sau sẽ làm tốt hơn!', "You'll do even better next time!", '다음엔 더 잘할 수 있어!'],
  'まいにち やると ぐんぐん のびるよ': ['Chơi mỗi ngày là tiến bộ nhanh lắm', "Play every day and you'll grow fast!", '매일 하면 쑥쑥 늘어!'],
  'はじめてだから れんしゅう しよう！': ['Lần đầu nên luyện tập trước nhé!', "It's your first time, so let's practise!", '처음이니까 연습해 보자!'],
  'じょうず！ つぎは ほんばん だよ！': ['Giỏi lắm! Tiếp theo là chơi thật nhé!', 'Well done! Next is the real one!', '잘했어! 다음은 진짜야!'],
  'スタンプを あつめると あそべるよ': ['Sưu tầm con dấu là chơi được nhé', 'Collect stamps to play this', '도장을 모으면 할 수 있어'],
  'ケロはかせが しゃべるよ！': ['Giáo sư Kero sẽ nói nhé!', 'Dr. Kero will talk!', '케로 박사가 말할게!'],

  // ---------------------------------------------------------------- overlays
  'やったね！': ['Làm được rồi!', 'You did it!', '해냈다!'],
  'はなまる スタンプ！': ['Con dấu bông hoa!', 'Flower stamp!', '꽃 도장!'],
  'スタンプ ゲット！': ['Được con dấu!', 'You got a stamp!', '도장 획득!'],
  'スタンプ {n}こめ！': ['Con dấu thứ {n}!', 'Stamp No. {n}!', '{n}번째 도장!'],
  'あたらしい トレーニング！': ['Bài luyện tập mới!', 'New training!', '새 트레이닝!'],
  '「{name}」で あそべるよ': ['Giờ chơi được “{name}” rồi', 'You can play “{name}” now', '이제 「{name}」 할 수 있어'],
  'あたらしい きょく！': ['Bài hát mới!', 'New song!', '새 노래!'],
  'ピアノで「{name}」が ひけるよ': ['Giờ đàn được bài “{name}” rồi', 'You can play “{name}” on the piano', '이제 피아노로 「{name}」 칠 수 있어'],
  'じょうず！': ['Giỏi lắm!', 'Well done!', '잘했어!'],
  'つぎは ほんばん だよ！': ['Tiếp theo là chơi thật nhé!', 'Next is the real one!', '다음은 진짜야!'],
  'ほんばん': ['Chơi thật', 'Real round', '진짜 하기'],
  'きょうは たくさん がんばったね！': ['Hôm nay cố gắng nhiều rồi!', 'You worked hard today!', '오늘 정말 열심히 했어!'],
  'つづきは また あした！': ['Mai chơi tiếp nhé!', 'More tomorrow!', '내일 또 하자!'],
  'もうすこし': ['Thêm chút nữa', 'A bit more', '조금 더'],
  'おしまい': ['Nghỉ thôi', 'Stop here', '그만할래'],

  // ---------------------------------------------------------------- the daily check
  'きょうの あたまチェック': ['Kiểm tra trí não hôm nay', "Today's Brain Check", '오늘의 두뇌 체크'],
  'きょうの あたまチェック！ 3つの テストを するよ': ['Kiểm tra trí não hôm nay! Mình làm 3 bài nhé', "Today's brain check! We'll do 3 tests", '오늘의 두뇌 체크! 테스트 3개를 할 거야'],
  'きょうは もう チェック したよ。 れんしゅうで やってみよう': ['Hôm nay đã kiểm tra rồi. Chơi luyện tập nhé', "You've already checked today. Let's practise", '오늘은 이미 체크했어. 연습으로 해 보자'],
  'よく できました！ つぎは {name}': ['Giỏi lắm! Tiếp theo là {name}', 'Well done! Next is {name}', '잘했어! 다음은 {name}'],
  'のうねんれいは {age}さい！': ['Tuổi não là {age}!', 'Your brain age is {age}!', '두뇌 나이는 {age}세!'],
  'きょうの あたまは {animal}！': ['Trí não hôm nay là {animal}!', "Today's brain: {animal}!", '오늘의 두뇌는 {animal}!'],
  '3つの テストで\nきょうの あたまを しらべるよ！': ['3 bài kiểm tra\nxem trí não hôm nay thế nào!', '3 tests to see\nhow your brain is today!', '3가지 테스트로\n오늘의 두뇌를 알아봐!'],
  'きょうは もう チェック したよ。\nれんしゅうで やってみよう！': ['Hôm nay đã kiểm tra rồi.\nChơi luyện tập nhé!', "You've already checked today.\nLet's practise!", '오늘은 이미 체크했어.\n연습으로 해 보자!'],
  'つぎは「{name}」だよ': ['Tiếp theo: “{name}”', 'Next: “{name}”', '다음은 「{name}」'],
  'のうねんれい <b>{age}</b> さい': ['Tuổi não <b>{age}</b>', 'Brain age <b>{age}</b>', '두뇌 나이 <b>{age}</b>세'],
  'きょうの あたまは<br><b>{animal}</b>': ['Trí não hôm nay:<br><b>{animal}</b>', "Today's brain:<br><b>{animal}</b>", '오늘의 두뇌는<br><b>{animal}</b>'],
  'おわる': ['Kết thúc', 'Finish', '끝내기'],
  'ぜんぶ すごいね！': ['Cái gì cũng giỏi!', 'Great at everything!', '다 대단해!'],
  'はやさが とくい だね！': ['Tốc độ là điểm mạnh nhé!', 'Speed is your strong point!', '속도가 특기구나!'],
  'きおくが とくい だね！': ['Trí nhớ là điểm mạnh nhé!', 'Memory is your strong point!', '기억력이 특기구나!'],
  'がまんが とくい だね！': ['Kiên nhẫn là điểm mạnh nhé!', 'Self-control is your strong point!', '참을성이 특기구나!'],
  '\n（れんしゅう なので きろくは しないよ）': ['\n(Luyện tập nên không ghi lại)', '\n(Just practice, so it isn\'t saved)', '\n(연습이라 기록하지 않아)'],

  // ---------------------------------------------------------------- stamps and records
  '{y}ねん {m}がつ': ['Tháng {m} năm {y}', '{mon} {y}', '{y}년 {m}월'],
  'あと <b>{n}こ</b> で<br>「{name}」が ふえるよ！': ['Thêm <b>{n}</b> con dấu nữa<br>là có “{name}”!', '<b>{n}</b> more stamps<br>and “{name}” opens!', '<b>{n}개</b> 더 모으면<br>「{name}」가 생겨!'],
  'あと <b>{n}こ</b> で<br>ピアノの「{name}」が ふえるよ！': ['Thêm <b>{n}</b> con dấu nữa<br>là có bài “{name}”!', '<b>{n}</b> more stamps<br>for the song “{name}”!', '<b>{n}개</b> 더 모으면<br>피아노 곡 「{name}」가 생겨!'],
  'ぜんぶ あいたよ！ まいにち つづけて<br>はなまるを あつめよう！': ['Mở hết rồi! Chơi đều mỗi ngày<br>để sưu tầm dấu bông hoa nhé!', 'Everything is open! Keep playing<br>every day to collect flower stamps!', '전부 열렸어! 매일 계속해서<br>꽃 도장을 모으자!'],
  'まだ だよ': ['Chưa có', 'Not yet', '아직이야'],
  'まだ きろくが ないよ': ['Chưa có kỷ lục', 'No records yet', '아직 기록이 없어'],
  'いちばん いい きろく：{best}': ['Kỷ lục tốt nhất: {best}', 'Best record: {best}', '최고 기록: {best}'],
  'あそんだ かず：{n}かい': ['Số lần chơi: {n}', 'Times played: {n}', '해 본 횟수: {n}번'],

  // ---------------------------------------------------------------- piano songs
  'きらきらぼし': ['Ngôi sao lấp lánh', 'Twinkle Twinkle', '반짝반짝 작은 별'],
  'かえるのうた': ['Bài hát chú ếch', 'The Frog Song', '개구리 노래'],
  'メリーさんの ひつじ': ['Chú cừu của Mary', 'Mary Had a Little Lamb', '메리의 어린 양'],
  'ちょうちょう': ['Bươm bướm', 'Butterfly', '나비야'],
  'よろこびの うた': ['Khúc hoan ca', 'Ode to Joy', '환희의 송가'],
  'ロンドンばし': ['Cầu London', 'London Bridge', '런던 다리'],
  'ジングルベル': ['Jingle Bells', 'Jingle Bells', '징글벨'],
  'ゆかいな まきば': ['Nông trại vui vẻ', 'Old MacDonald', '맥도널드 할아버지'],
  'こげ こげ ボート': ['Chèo thuyền', 'Row, Row, Row Your Boat', '노 젓기 노래'],
  'がっこうの チャイム': ['Chuông trường học', 'School Chime', '학교 종소리'],
  'ホット クロス バンズ': ['Hot Cross Buns', 'Hot Cross Buns', '핫 크로스 번'],
  'せいじゃの こうしん': ['Các thánh diễu hành', 'When the Saints', '성자의 행진'],
  'おお スザンナ': ['Ôi Susanna', 'Oh! Susanna', '오 수재너'],
  'いえじ': ['Đường về nhà', 'Going Home', '꿈속의 고향'],
  'こもりうた': ['Bài hát ru', 'Lullaby', '자장가'],
  'ドレミの かいだん': ['Cầu thang Đô Rê Mi', 'Up the Keys', '도레미 계단'],

  // ---------------------------------------------------------------- shop
  'ケロちゃん': ['Kero', 'Kero', '케로'],
  'ミミちゃん': ['Mimi', 'Mimi', '미미'],
  'ニャーちゃん': ['Meo Meo', 'Meow', '야옹이'],
  'ワンちゃん': ['Gâu Gâu', 'Woof', '멍멍이'],
  '★を つかって おともだちを ふやそう！': ['Dùng ★ để có thêm bạn mới nhé!', 'Use your ★ to make new friends!', '★로 새 친구를 만들자!'],
  'つかってる': ['Đang chọn', 'Chosen', '함께하는 중'],
  'えらぶ': ['Chọn', 'Choose', '고르기'],
  '{star}{price} で かう': ['Mua {star}{price}', 'Buy {star}{price}', '{star}{price}에 사기'],
  'あと ★{n} で かえるよ': ['Cần thêm ★{n} nữa là mua được', '{n} more ★ to buy it', '★{n}개만 더 모으면 살 수 있어'],
  '{name}を<br>{star}{price} で かう？': ['Mua {name}<br>với {star}{price} nhé?', 'Buy {name}<br>for {star}{price}?', '{name}를<br>{star}{price}에 살까?'],
  '{name}が なかまに なったよ！': ['{name} đã thành bạn rồi!', '{name} is your friend now!', '{name}가 친구가 되었어!'],
  'かう': ['Mua', 'Buy', '살래'],

  // ---------------------------------------------------------------- two players
  'つみきは いくつ？': ['Có bao nhiêu khối?', 'How many blocks?', '블록은 몇 개?'],
  'みどり': ['Xanh lá', 'Green', '초록'],
  'ピンク': ['Hồng', 'Pink', '분홍'],
  'みどりの かち！': ['Xanh lá thắng!', 'Green wins!', '초록 승리!'],
  'ピンクの かち！': ['Hồng thắng!', 'Pink wins!', '분홍 승리!'],
  'なにで あそぶ？': ['Chơi trò gì?', 'What shall we play?', '뭐 하고 놀까?'],
  'むずかしさ': ['Độ khó', 'Level', '난이도'],
  'うえ（ピンク）': ['Trên (hồng)', 'Top (pink)', '위 (분홍)'],
  'した（みどり）': ['Dưới (xanh lá)', 'Bottom (green)', '아래 (초록)'],
  'おとなが まつ びょう': ['Người lớn chờ (giây)', 'Grown-up waits (s)', '어른 기다리기 (초)'],
  'スマホを つくえに おいて<br>むかいあって あそんでね': ['Đặt điện thoại lên bàn<br>rồi ngồi đối diện nhau chơi nhé', 'Put the phone on a table<br>and play facing each other', '스마트폰을 책상에 놓고<br>마주 보고 놀아'],
  '{n}てん': ['{n} điểm', '{n} pts', '{n}점'],
  'まってね': ['Chờ nhé', 'Wait', '기다려'],
  'ひきわけ！': ['Hòa!', "It's a tie!", '비겼다!'],
  'かち！': ['Thắng rồi!', 'You win!', '이겼다!'],
  'まけ… つぎは がんばろう': ['Thua rồi… Lần sau cố lên nhé', 'You lose… Try again next time', '졌어… 다음엔 힘내자'],
  'こたえ：{a}': ['Đáp án: {a}', 'Answer: {a}', '정답: {a}'],

  // ---------------------------------------------------------------- grown-ups (family mode, admin)
  '管理者パスワード': ['Mật khẩu quản lý', 'Admin password', '관리자 비밀번호'],
  '閉じる': ['Đóng', 'Close', '닫기'],
  '管理者メニュー': ['Menu quản lý', 'Admin menu', '관리자 메뉴'],
  'ユーザー（かぞくモード）': ['Người chơi (chế độ gia đình)', 'Players (family mode)', '사용자 (가족 모드)'],
  'ユーザー': ['Người chơi', 'Players', '사용자'],
  'ユーザーを ふやす': ['Thêm người chơi', 'Add a player', '사용자 추가'],
  'ユーザーの せってい': ['Cài đặt người chơi', 'Player settings', '사용자 설정'],
  'なまえ': ['Tên', 'Name', '이름'],
  'れい：はなこ': ['Ví dụ: Na', 'e.g. Hana', '예: 하나'],
  'へんしゅう': ['Sửa', 'Edit', '편집'],
  'もう一度で けす': ['Nhấn lần nữa để xóa', 'Tap again to delete', '한 번 더 누르면 삭제'],
  'いまの ユーザー：{name}（{type}）<br>スタンプ {s}　あつめた★ {a}　つかった★ {b}': ['Người chơi: {name} ({type})<br>Con dấu {s}　★ đã nhặt {a}　★ đã dùng {b}', 'Player: {name} ({type})<br>Stamps {s}　★ collected {a}　★ spent {b}', '지금 사용자: {name} ({type})<br>도장 {s}　모은 ★ {a}　쓴 ★ {b}'],
  '全トレーニング解放：{v}': ['Mở mọi bài luyện: {v}', 'Unlock all trainings: {v}', '모든 트레이닝 열기: {v}'],
  'オン': ['Bật', 'On', '켬'],
  'オフ': ['Tắt', 'Off', '끔'],
  'おしまいの声かけ：{v}': ['Nhắc nghỉ: {v}', 'Time-to-stop reminder: {v}', '그만하기 알림: {v}'],
  '{n}つで': ['sau {n} bài', 'after {n}', '{n}개 후'],
  'しない': ['Không', 'Off', '안 함'],
  'このユーザーの記録をリセット': ['Xóa kỷ lục của người chơi này', "Reset this player's records", '이 사용자 기록 초기화'],
  'もう一度押すと消えます': ['Nhấn lần nữa để xóa', 'Press again to erase', '한 번 더 누르면 지워져요'],
  'ケロはかせの こえ：{credit}。': ['Giọng Giáo sư Kero: {credit}. ', "Dr. Kero's voice: {credit}. ", '케로 박사 목소리: {credit}. '],
  '日本語の こえ：{credit}。': ['Giọng tiếng Nhật: {credit}. ', 'Japanese voice: {credit}. ', '일본어 목소리: {credit}. '],
  'パソコンでの確認中は 音も声も出しません（アドレスに ?sound=1 を付けると出ます）。': ['Khi kiểm tra trên máy tính, trò chơi không phát âm thanh hay giọng nói (thêm ?sound=1 vào địa chỉ để bật).', 'While testing on a computer there is no sound or voice (add ?sound=1 to the address to hear it).', '컴퓨터에서 확인할 때는 소리도 목소리도 나오지 않아요 (주소에 ?sound=1을 붙이면 나와요).'],
  'この ことばの こえ：スマホの 読み上げの 声が 見つかりました。': ['Giọng tiếng Việt: đã tìm thấy giọng đọc trên điện thoại.', "English voice: the phone's text-to-speech voice was found.", '한국어 목소리: 휴대폰의 음성 읽기 목소리를 찾았어요.'],
  'この ことばの こえ：スマホに 声が 見つかりません。Android の「設定 → システム → 言語と入力 → テキスト読み上げ」で この ことばの 音声データを 入れると しゃべります。': ['Giọng tiếng Việt: chưa tìm thấy giọng đọc trên điện thoại. Vào “Cài đặt → Hệ thống → Ngôn ngữ và phương thức nhập → Chuyển văn bản thành giọng nói” của Android, tải dữ liệu giọng tiếng Việt thì Giáo sư Kero sẽ nói.', 'English voice: no voice was found on the phone. Install the English voice data in Android “Settings → System → Languages & input → Text-to-speech output” and Dr. Kero will talk.', '한국어 목소리: 휴대폰에서 목소리를 찾지 못했어요. Android의 “설정 → 시스템 → 언어 및 입력 → 텍스트 음성 변환”에서 한국어 음성 데이터를 설치하면 말해요.'],
  'この ことばの こえ：このブラウザでは 使えません。': ['Giọng tiếng Việt: trình duyệt này không hỗ trợ.', "English voice: this browser can't speak.", '한국어 목소리: 이 브라우저에서는 쓸 수 없어요.']
});

// The big title, one line per row (each letter hops on its own).
var GAME_LOGO = { ja: ['ケロちゃん', 'あたま ぐんぐん'], vi: ['Kero', 'Luyện Não'], en: ['Kero', 'Brain Boost'], ko: ['케로', '두뇌 쑥쑥'] };

/* What depends on the letters of each language (app.js puts it into the data at the start):
   keys: the piano's note names; week: the days on the stamp calendar (Sunday first);
   seq: the letters of じゅんばん (1 → a → 2 → b ...); letters: extra tiles of ことば つくり;
   words: the picture names that ことば つくり spells (a picture without a word is left out);
   len: the word lengths of ことば つくり for each level. */
var GUNGUN_LANG = {
  vi: {
    keys: ['Đô', 'Rê', 'Mi', 'Pha', 'Son', 'La', 'Si', 'Đô'],
    week: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
    seq: 'aăâbcdđeêg',
    letters: 'abcdđeghiklmnoôơpqrstuưvxyáàảạéèóòúù',
    words: {
      dog: 'chó', cat: 'mèo', shoe: 'giày', star: 'sao', flower: 'hoa', crab: 'cua', peach: 'đào', apple: 'táo',
      strawberry: 'dâu', egg: 'trứng', frog: 'ếch', rabbit: 'thỏ', grapes: 'nho', mandarin: 'quýt', fish: 'cá',
      hat: 'mũ', car: 'xe', balloon: 'bóng', pencil: 'bút', snail: 'ốc',
      bear: 'gấu', cow: 'bò', turtle: 'rùa', monkey: 'khỉ', elephant: 'voi', moon: 'trăng', cloud: 'mây',
      house: 'nhà', boat: 'thuyền', mushroom: 'nấm', glasses: 'kính', banana: 'chuối', lemon: 'chanh', mouse: 'chuột',
      drum: 'trống', book: 'sách', scissors: 'kéo', ghost: 'ma', owl: 'cú', corn: 'ngô'
    },
    len: { e: [2, 3], n: [3, 3], h: [3, 5], ae: [3, 4], a: [3, 5], ah: [3, 5], practice: [2, 2] }
  },
  en: {
    keys: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
    week: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    seq: 'ABCDEFGHIJ',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    words: {
      dog: 'DOG', cat: 'CAT', shoe: 'SHOE', star: 'STAR', flower: 'FLOWER', crab: 'CRAB', peach: 'PEACH', apple: 'APPLE',
      egg: 'EGG', chick: 'CHICK', frog: 'FROG', rabbit: 'RABBIT', grapes: 'GRAPES', mandarin: 'ORANGE', fish: 'FISH',
      hat: 'HAT', car: 'CAR', balloon: 'BALLOON', mitten: 'MITTEN', pencil: 'PENCIL', snail: 'SNAIL', cherry: 'CHERRY',
      bear: 'BEAR', cow: 'COW', turtle: 'TURTLE', monkey: 'MONKEY', elephant: 'ELEPHANT', moon: 'MOON', cloud: 'CLOUD',
      house: 'HOUSE', boat: 'BOAT', octopus: 'OCTOPUS', bread: 'BREAD', top: 'TOP', rainbow: 'RAINBOW', mushroom: 'MUSHROOM',
      glasses: 'GLASSES', banana: 'BANANA', lemon: 'LEMON', tomato: 'TOMATO', mouse: 'MOUSE', panda: 'PANDA', giraffe: 'GIRAFFE',
      drum: 'DRUM', book: 'BOOK', scissors: 'SCISSORS', ghost: 'GHOST', plane: 'PLANE', lion: 'LION', penguin: 'PENGUIN',
      owl: 'OWL', acorn: 'ACORN', carrot: 'CARROT', crown: 'CROWN', snowman: 'SNOWMAN', beetle: 'BEETLE', corn: 'CORN',
      ladybug: 'LADYBUG'
    },
    len: { e: [3, 4], n: [4, 5], h: [5, 6], ae: [4, 5], a: [5, 7], ah: [6, 6], practice: [3, 3] }
  },
  ko: {
    keys: ['도', '레', '미', '파', '솔', '라', '시', '도'],
    week: ['일', '월', '화', '수', '목', '금', '토'],
    seq: '가나다라마바사아자차',
    letters: '가나다라마바사아자차카타파하고노도로모보소오조호구누두루무부수우주후',
    words: {
      dog: '개', cat: '고양이', umbrella: '우산', shoe: '신발', star: '별', flower: '꽃', crab: '게', peach: '복숭아',
      apple: '사과', strawberry: '딸기', egg: '달걀', chick: '병아리', frog: '개구리', rabbit: '토끼', watermelon: '수박',
      grapes: '포도', mandarin: '귤', fish: '물고기', hat: '모자', car: '자동차', riceball: '주먹밥', balloon: '풍선',
      sunflower: '해바라기', mitten: '장갑', pencil: '연필', snail: '달팽이', cherry: '체리',
      bear: '곰', cow: '소', turtle: '거북이', monkey: '원숭이', elephant: '코끼리', moon: '달', cloud: '구름',
      house: '집', boat: '배', octopus: '문어', bread: '빵', top: '팽이', rainbow: '무지개', mushroom: '버섯',
      glasses: '안경', banana: '바나나', lemon: '레몬', tomato: '토마토', mouse: '생쥐', panda: '판다', giraffe: '기린',
      drum: '북', book: '그림책', scissors: '가위', ghost: '유령', plane: '비행기', lion: '사자', penguin: '펭귄',
      owl: '부엉이', acorn: '도토리', carrot: '당근', crown: '왕관', snowman: '눈사람', beetle: '장수풍뎅이', corn: '옥수수',
      ladybug: '무당벌레'
    },
    len: { e: [2, 2], n: [3, 3], h: [3, 4], ae: [2, 3], a: [2, 4], ah: [3, 4], practice: [2, 2] }
  }
};
